# Project: binmod
# Makefile created by Steve Chang
# Date modified: 2024.11.30

LIBNAME = libmain.a

DIR = src

SUBDIR =

INCLUDE = \
	utility \

SRCS = $(wildcard *.c)

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
